import { ThemeConfig } from './theme-config'

// Tema Amethyst Haze (basado en haze1.css)
export const amethystHazeTheme: ThemeConfig = {
  id: 'amethyst-haze',
  name: 'Amethyst Haze',
  description: 'Tema elegante con tonos violeta y rosa para ambientes sofisticados',
  category: 'custom',
  colors: {
    light: {
      background: '#f8f7fa',
      foreground: '#3d3c4f',
      card: '#ffffff',
      'card-foreground': '#3d3c4f',
      popover: '#ffffff',
      'popover-foreground': '#3d3c4f',
      primary: '#8a79ab',
      'primary-foreground': '#f8f7fa',
      secondary: '#dfd9ec',
      'secondary-foreground': '#3d3c4f',
      muted: '#dcd9e3',
      'muted-foreground': '#6b6880',
      accent: '#e6a5b8',
      'accent-foreground': '#4b2e36',
      destructive: '#d95c5c',
      'destructive-foreground': '#f8f7fa',
      border: '#cec9d9',
      input: '#eae7f0',
      ring: '#8a79ab',
      'chart-1': '#8a79ab',
      'chart-2': '#e6a5b8',
      'chart-3': '#77b8a1',
      'chart-4': '#f0c88d',
      'chart-5': '#a0bbe3',
      sidebar: '#f1eff5',
      'sidebar-foreground': '#3d3c4f',
      'sidebar-primary': '#8a79ab',
      'sidebar-primary-foreground': '#f8f7fa',
      'sidebar-accent': '#e6a5b8',
      'sidebar-accent-foreground': '#4b2e36',
      'sidebar-border': '#d7d2e0',
      'sidebar-ring': '#8a79ab'
    },
    dark: {
      background: '#1a1823',
      foreground: '#e0ddef',
      card: '#232030',
      'card-foreground': '#e0ddef',
      popover: '#232030',
      'popover-foreground': '#e0ddef',
      primary: '#a995c9',
      'primary-foreground': '#1a1823',
      secondary: '#5a5370',
      'secondary-foreground': '#e0ddef',
      muted: '#242031',
      'muted-foreground': '#a09aad',
      accent: '#372e3f',
      'accent-foreground': '#f2b8c6',
      destructive: '#e57373',
      'destructive-foreground': '#1a1823',
      border: '#302c40',
      input: '#2a273a',
      ring: '#a995c9',
      'chart-1': '#a995c9',
      'chart-2': '#f2b8c6',
      'chart-3': '#77b8a1',
      'chart-4': '#f0c88d',
      'chart-5': '#a0bbe3',
      sidebar: '#16141e',
      'sidebar-foreground': '#e0ddef',
      'sidebar-primary': '#a995c9',
      'sidebar-primary-foreground': '#1a1823',
      'sidebar-accent': '#372e3f',
      'sidebar-accent-foreground': '#f2b8c6',
      'sidebar-border': '#2a273a',
      'sidebar-ring': '#a995c9'
    }
  },
  touchOptimizations: {
    buttonMinSize: '2.75rem',
    touchSpacing: '0.5rem',
    rippleEffects: true,
    hoverFeedback: true
  },
  typography: {
    baseFontSize: '16px',
    fontFamily: 'Geist, sans-serif'
  },
  preview: {
    primaryColor: '#8a79ab',
    secondaryColor: '#e6a5b8',
    backgroundColor: '#f8f7fa'
  }
}

// Tema Bubble (basado en bubble.css)
export const bubbleTheme: ThemeConfig = {
  id: 'bubble',
  name: 'Bubble',
  description: 'Tema vibrante y divertido con colores bubble y efectos modernos',
  category: 'custom',
  colors: {
    light: {
      background: '#f6e6ee',
      foreground: '#5b5b5b',
      card: '#fdedc9',
      'card-foreground': '#5b5b5b',
      popover: '#ffffff',
      'popover-foreground': '#5b5b5b',
      primary: '#d04f99',
      'primary-foreground': '#ffffff',
      secondary: '#8acfd1',
      'secondary-foreground': '#333333',
      muted: '#b2e1eb',
      'muted-foreground': '#7a7a7a',
      accent: '#fbe2a7',
      'accent-foreground': '#333333',
      destructive: '#f96f70',
      'destructive-foreground': '#ffffff',
      border: '#d04f99',
      input: '#e4e4e4',
      ring: '#e670ab',
      'chart-1': '#e670ab',
      'chart-2': '#84d2e2',
      'chart-3': '#fbe2a7',
      'chart-4': '#f3a0ca',
      'chart-5': '#d7488e',
      sidebar: '#f8d8ea',
      'sidebar-foreground': '#333333',
      'sidebar-primary': '#ec4899',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#f9a8d4',
      'sidebar-accent-foreground': '#333333',
      'sidebar-border': '#f3e8ff',
      'sidebar-ring': '#ec4899'
    },
    dark: {
      background: '#12242e',
      foreground: '#f3e3ea',
      card: '#1c2e38',
      'card-foreground': '#f3e3ea',
      popover: '#1c2e38',
      'popover-foreground': '#f3e3ea',
      primary: '#fbe2a7',
      'primary-foreground': '#12242e',
      secondary: '#e4a2b1',
      'secondary-foreground': '#12242e',
      muted: '#24272b',
      'muted-foreground': '#e4a2b1',
      accent: '#c67b96',
      'accent-foreground': '#f3e3ea',
      destructive: '#e35ea4',
      'destructive-foreground': '#12242e',
      border: '#324859',
      input: '#20333d',
      ring: '#50afb6',
      'chart-1': '#50afb6',
      'chart-2': '#e4a2b1',
      'chart-3': '#c67b96',
      'chart-4': '#175c6c',
      'chart-5': '#24272b',
      sidebar: '#101f28',
      'sidebar-foreground': '#f3f4f6',
      'sidebar-primary': '#ec4899',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#f9a8d4',
      'sidebar-accent-foreground': '#1f2937',
      'sidebar-border': '#374151',
      'sidebar-ring': '#ec4899'
    }
  },
  touchOptimizations: {
    buttonMinSize: '2.75rem',
    touchSpacing: '0.5rem',
    rippleEffects: true,
    hoverFeedback: true
  },
  typography: {
    baseFontSize: '16px',
    fontFamily: 'Poppins, sans-serif'
  },
  preview: {
    primaryColor: '#d04f99',
    secondaryColor: '#8acfd1',
    backgroundColor: '#f6e6ee'
  }
}

// Tema Restaurant Professional - Cálido y profesional
export const restaurantProfessionalTheme: ThemeConfig = {
  id: 'restaurant-professional',
  name: 'Restaurant Professional',
  description: 'Tema cálido y profesional para restaurantes elegantes',
  category: 'restaurant',
  colors: {
    light: {
      background: '#faf9f6',
      foreground: '#2c2a26',
      card: '#ffffff',
      'card-foreground': '#2c2a26',
      popover: '#ffffff',
      'popover-foreground': '#2c2a26',
      primary: '#b8860b',
      'primary-foreground': '#ffffff',
      secondary: '#f5f0e8',
      'secondary-foreground': '#2c2a26',
      muted: '#f0ebe2',
      'muted-foreground': '#6b6559',
      accent: '#cd853f',
      'accent-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e5ddd1',
      input: '#f9f6f0',
      ring: '#b8860b',
      'chart-1': '#b8860b',
      'chart-2': '#cd853f',
      'chart-3': '#8b7355',
      'chart-4': '#daa520',
      'chart-5': '#f4a460',
      sidebar: '#f7f3eb',
      'sidebar-foreground': '#2c2a26',
      'sidebar-primary': '#b8860b',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#cd853f',
      'sidebar-accent-foreground': '#ffffff',
      'sidebar-border': '#e8e0d4',
      'sidebar-ring': '#b8860b'
    },
    dark: {
      background: '#1a1815',
      foreground: '#f5f2ed',
      card: '#25221e',
      'card-foreground': '#f5f2ed',
      popover: '#25221e',
      'popover-foreground': '#f5f2ed',
      primary: '#daa520',
      'primary-foreground': '#1a1815',
      secondary: '#3d3832',
      'secondary-foreground': '#f5f2ed',
      muted: '#2a271f',
      'muted-foreground': '#a69b8a',
      accent: '#f4a460',
      'accent-foreground': '#1a1815',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#3d3832',
      input: '#2a271f',
      ring: '#daa520',
      'chart-1': '#daa520',
      'chart-2': '#f4a460',
      'chart-3': '#cd853f',
      'chart-4': '#b8860b',
      'chart-5': '#8b7355',
      sidebar: '#141210',
      'sidebar-foreground': '#f5f2ed',
      'sidebar-primary': '#daa520',
      'sidebar-primary-foreground': '#1a1815',
      'sidebar-accent': '#f4a460',
      'sidebar-accent-foreground': '#1a1815',
      'sidebar-border': '#2a271f',
      'sidebar-ring': '#daa520'
    }
  },
  touchOptimizations: {
    buttonMinSize: '3rem',
    touchSpacing: '0.75rem',
    rippleEffects: true,
    hoverFeedback: true
  },
  preview: {
    primaryColor: '#b8860b',
    secondaryColor: '#cd853f',
    backgroundColor: '#faf9f6'
  }
}

// Tema Modern Cafe - Minimalista y fresco
export const modernCafeTheme: ThemeConfig = {
  id: 'modern-cafe',
  name: 'Modern Cafe',
  description: 'Diseño minimalista y fresco ideal para cafeterías modernas',
  category: 'cafe',
  colors: {
    light: {
      background: '#fcfcfc',
      foreground: '#1a1a1a',
      card: '#ffffff',
      'card-foreground': '#1a1a1a',
      popover: '#ffffff',
      'popover-foreground': '#1a1a1a',
      primary: '#16a34a',
      'primary-foreground': '#ffffff',
      secondary: '#f1f5f9',
      'secondary-foreground': '#1a1a1a',
      muted: '#f8fafc',
      'muted-foreground': '#6b7280',
      accent: '#059669',
      'accent-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e2e8f0',
      input: '#f8fafc',
      ring: '#16a34a',
      'chart-1': '#16a34a',
      'chart-2': '#059669',
      'chart-3': '#10b981',
      'chart-4': '#34d399',
      'chart-5': '#6ee7b7',
      sidebar: '#f9fafb',
      'sidebar-foreground': '#1a1a1a',
      'sidebar-primary': '#16a34a',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#059669',
      'sidebar-accent-foreground': '#ffffff',
      'sidebar-border': '#e5e7eb',
      'sidebar-ring': '#16a34a'
    },
    dark: {
      background: '#0f172a',
      foreground: '#f1f5f9',
      card: '#1e293b',
      'card-foreground': '#f1f5f9',
      popover: '#1e293b',
      'popover-foreground': '#f1f5f9',
      primary: '#22c55e',
      'primary-foreground': '#0f172a',
      secondary: '#334155',
      'secondary-foreground': '#f1f5f9',
      muted: '#1e293b',
      'muted-foreground': '#94a3b8',
      accent: '#10b981',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#334155',
      input: '#1e293b',
      ring: '#22c55e',
      'chart-1': '#22c55e',
      'chart-2': '#10b981',
      'chart-3': '#34d399',
      'chart-4': '#6ee7b7',
      'chart-5': '#a7f3d0',
      sidebar: '#0c1426',
      'sidebar-foreground': '#f1f5f9',
      'sidebar-primary': '#22c55e',
      'sidebar-primary-foreground': '#0f172a',
      'sidebar-accent': '#10b981',
      'sidebar-accent-foreground': '#0f172a',
      'sidebar-border': '#1e293b',
      'sidebar-ring': '#22c55e'
    }
  },
  touchOptimizations: {
    buttonMinSize: '2.75rem',
    touchSpacing: '1rem',
    rippleEffects: false,
    hoverFeedback: true
  },
  preview: {
    primaryColor: '#16a34a',
    secondaryColor: '#059669',
    backgroundColor: '#fcfcfc'
  }
}

// Tema Night Bar - Oscuro con acentos neón
export const nightBarTheme: ThemeConfig = {
  id: 'night-bar',
  name: 'Night Bar',
  description: 'Tema oscuro con acentos neón para bares y locales nocturnos',
  category: 'bar',
  colors: {
    light: {
      background: '#fafafa',
      foreground: '#1a1a1a',
      card: '#ffffff',
      'card-foreground': '#1a1a1a',
      popover: '#ffffff',
      'popover-foreground': '#1a1a1a',
      primary: '#3b82f6',
      'primary-foreground': '#ffffff',
      secondary: '#f1f5f9',
      'secondary-foreground': '#1a1a1a',
      muted: '#f8fafc',
      'muted-foreground': '#6b7280',
      accent: '#8b5cf6',
      'accent-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e2e8f0',
      input: '#f8fafc',
      ring: '#3b82f6',
      'chart-1': '#3b82f6',
      'chart-2': '#8b5cf6',
      'chart-3': '#06b6d4',
      'chart-4': '#10b981',
      'chart-5': '#f59e0b',
      sidebar: '#f9fafb',
      'sidebar-foreground': '#1a1a1a',
      'sidebar-primary': '#3b82f6',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#8b5cf6',
      'sidebar-accent-foreground': '#ffffff',
      'sidebar-border': '#e5e7eb',
      'sidebar-ring': '#3b82f6'
    },
    dark: {
      background: '#080808',
      foreground: '#e0e0e0',
      card: '#111111',
      'card-foreground': '#e0e0e0',
      popover: '#111111',
      'popover-foreground': '#e0e0e0',
      primary: '#0ea5e9',
      'primary-foreground': '#080808',
      secondary: '#1a1a1a',
      'secondary-foreground': '#e0e0e0',
      muted: '#161616',
      'muted-foreground': '#9ca3af',
      accent: '#a855f7',
      'accent-foreground': '#080808',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#262626',
      input: '#161616',
      ring: '#0ea5e9',
      'chart-1': '#0ea5e9',
      'chart-2': '#a855f7',
      'chart-3': '#06b6d4',
      'chart-4': '#10b981',
      'chart-5': '#f59e0b',
      sidebar: '#050505',
      'sidebar-foreground': '#e0e0e0',
      'sidebar-primary': '#0ea5e9',
      'sidebar-primary-foreground': '#080808',
      'sidebar-accent': '#a855f7',
      'sidebar-accent-foreground': '#080808',
      'sidebar-border': '#161616',
      'sidebar-ring': '#0ea5e9'
    }
  },
  touchOptimizations: {
    buttonMinSize: '3.5rem',
    touchSpacing: '0.75rem',
    rippleEffects: true,
    hoverFeedback: true
  },
  preview: {
    primaryColor: '#0ea5e9',
    secondaryColor: '#a855f7',
    backgroundColor: '#080808'
  }
}

// Tema High Contrast Accessibility
export const accessibilityTheme: ThemeConfig = {
  id: 'accessibility-high-contrast',
  name: 'High Contrast Accessibility',
  description: 'Tema de alto contraste optimizado para accesibilidad',
  category: 'accessibility',
  colors: {
    light: {
      background: '#ffffff',
      foreground: '#000000',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#0066cc',
      'primary-foreground': '#ffffff',
      secondary: '#f0f0f0',
      'secondary-foreground': '#000000',
      muted: '#e6e6e6',
      'muted-foreground': '#333333',
      accent: '#ff6600',
      'accent-foreground': '#ffffff',
      destructive: '#cc0000',
      'destructive-foreground': '#ffffff',
      border: '#cccccc',
      input: '#ffffff',
      ring: '#0066cc',
      'chart-1': '#0066cc',
      'chart-2': '#ff6600',
      'chart-3': '#009900',
      'chart-4': '#cc0099',
      'chart-5': '#ffcc00',
      sidebar: '#f8f8f8',
      'sidebar-foreground': '#000000',
      'sidebar-primary': '#0066cc',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#ff6600',
      'sidebar-accent-foreground': '#ffffff',
      'sidebar-border': '#cccccc',
      'sidebar-ring': '#0066cc'
    },
    dark: {
      background: '#000000',
      foreground: '#ffffff',
      card: '#1a1a1a',
      'card-foreground': '#ffffff',
      popover: '#1a1a1a',
      'popover-foreground': '#ffffff',
      primary: '#4d9fff',
      'primary-foreground': '#000000',
      secondary: '#333333',
      'secondary-foreground': '#ffffff',
      muted: '#262626',
      'muted-foreground': '#cccccc',
      accent: '#ff9933',
      'accent-foreground': '#000000',
      destructive: '#ff3333',
      'destructive-foreground': '#000000',
      border: '#666666',
      input: '#1a1a1a',
      ring: '#4d9fff',
      'chart-1': '#4d9fff',
      'chart-2': '#ff9933',
      'chart-3': '#33cc33',
      'chart-4': '#ff33cc',
      'chart-5': '#ffff33',
      sidebar: '#0d0d0d',
      'sidebar-foreground': '#ffffff',
      'sidebar-primary': '#4d9fff',
      'sidebar-primary-foreground': '#000000',
      'sidebar-accent': '#ff9933',
      'sidebar-accent-foreground': '#000000',
      'sidebar-border': '#333333',
      'sidebar-ring': '#4d9fff'
    }
  },
  touchOptimizations: {
    buttonMinSize: '3.5rem',
    touchSpacing: '1rem',
    rippleEffects: false,
    hoverFeedback: true
  },
  preview: {
    primaryColor: '#0066cc',
    secondaryColor: '#ff6600',
    backgroundColor: '#ffffff'
  }
}

// Array con todos los temas predefinidos
export const PRESET_THEMES: ThemeConfig[] = [
  amethystHazeTheme,
  bubbleTheme,
  restaurantProfessionalTheme,
  modernCafeTheme,
  nightBarTheme,
  accessibilityTheme
]

// Helper para obtener un tema por ID
export function getThemeById(id: string): ThemeConfig | undefined {
  return PRESET_THEMES.find(theme => theme.id === id)
}

// Helper para obtener temas por categoría
export function getThemesByCategory(category: ThemeConfig['category']): ThemeConfig[] {
  return PRESET_THEMES.filter(theme => theme.category === category)
}